using System.Net;
using System.Net.Http.Headers;
using System.Runtime.Versioning;
using System.Text;
using System.Text.Json;
using ClaudeUsage.Models;

namespace ClaudeUsage.Services;

/// Fetches live plan usage from the Claude.ai API using the Claude desktop
/// app's session cookies. Counterpart to api.go.
public sealed class UsageApi
{
    private static readonly HttpClient Http = CreateHttpClient();

    private static HttpClient CreateHttpClient()
    {
        // On Windows, WinHttpHandler uses the system's WinHTTP stack which has
        // a TLS fingerprint acceptable to Cloudflare, unlike SocketsHttpHandler.
        HttpMessageHandler handler = OperatingSystem.IsWindows()
            ? CreateWinHttpHandler()
            : new SocketsHttpHandler { PooledConnectionLifetime = TimeSpan.FromMinutes(5) };

        return new HttpClient(handler) { Timeout = TimeSpan.FromSeconds(15) };
    }

    [SupportedOSPlatform("windows")]
    private static WinHttpHandler CreateWinHttpHandler()
        => new() { SendTimeout = TimeSpan.FromSeconds(15) };

    // Must match the actual Claude desktop app UA so Cloudflare's cf_clearance cookie
    // (which was generated by the Electron app) validates against our requests.
    // Chrome/Electron versions read from Claude.exe embedded strings: Chrome/146.0.7680.216, Electron/41.6.1
    private static readonly string UserAgent =
        OperatingSystem.IsWindows() ? "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Claude/41.6.1 Chrome/146.0.7680.216 Electron/41.6.1 Safari/537.36" :
        OperatingSystem.IsMacOS()   ? "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Claude/41.6.1 Chrome/146.0.7680.216 Electron/41.6.1 Safari/537.36" :
                                      "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Claude/41.6.1 Chrome/146.0.7680.216 Electron/41.6.1 Safari/537.36";

    public sealed record Result(PlanUsage Usage, RateLimits Limits);

    public static async Task<Result> LoadAsync()
    {
        // Cookie reading touches the filesystem, SQLite and DPAPI synchronously;
        // push it off the UI thread.
        var cookies = await Task.Run(ClaudeCookies.Read);

        var encodedKey = PercentEncode(cookies.SessionKey);
        DiagnosticLog.Write($"LoadAsync: sessionKey.Length={cookies.SessionKey.Length}, encodedKey.Length={encodedKey.Length}, orgId={cookies.OrgId}");

        var usageUrl = $"https://claude.ai/api/organizations/{cookies.OrgId}/usage";
        var limitsUrl = $"https://claude.ai/api/organizations/{cookies.OrgId}/rate_limits";
        DiagnosticLog.Write($"LoadAsync: usageUrl={usageUrl}");

        var usage = await FetchAsync<PlanUsage>(usageUrl, encodedKey, cookies.RawOrgCookieValue, cookies.ExtraCookies);
        var limits = await FetchAsync<RateLimits>(limitsUrl, encodedKey, cookies.RawOrgCookieValue, cookies.ExtraCookies);

        return new Result(usage, limits);
    }

    private static async Task<T> FetchAsync<T>(string url, string encodedSessionKey,
        string rawOrgCookieValue, IReadOnlyDictionary<string, string>? extraCookies)
    {
        using var req = new HttpRequestMessage(HttpMethod.Get, url);

        var cookieSb = new StringBuilder();
        cookieSb.Append($"sessionKey={encodedSessionKey}");
        cookieSb.Append($"; lastActiveOrg={PercentEncode(rawOrgCookieValue)}");
        if (extraCookies is not null)
            foreach (var (name, value) in extraCookies)
                cookieSb.Append($"; {name}={PercentEncode(value)}");

        req.Headers.Add("Cookie", cookieSb.ToString());
        req.Headers.UserAgent.ParseAdd(UserAgent);
        req.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        req.Headers.Add("Accept-Language", "en-US,en;q=0.9");
        req.Headers.Add("Origin", "https://claude.ai");
        req.Headers.Add("Referer", "https://claude.ai/");
        req.Headers.Add("sec-fetch-dest", "empty");
        req.Headers.Add("sec-fetch-mode", "cors");
        req.Headers.Add("sec-fetch-site", "same-origin");
        req.Headers.Add("sec-ch-ua", "\"Chromium\";v=\"146\", \"Google Chrome\";v=\"146\", \"Not-A.Brand\";v=\"99\"");
        req.Headers.Add("sec-ch-ua-mobile", "?0");
        req.Headers.Add("sec-ch-ua-platform", "\"Windows\"");

        using var resp = await Http.SendAsync(req);
        if (resp.StatusCode is HttpStatusCode.Unauthorized or HttpStatusCode.Forbidden)
        {
            var body = await resp.Content.ReadAsStringAsync();
            DiagnosticLog.Write($"HTTP {(int)resp.StatusCode} {resp.StatusCode} — body: {body[..Math.Min(body.Length, 300)]}");
            throw new InvalidOperationException("session expired — open the Claude desktop app to refresh");
        }
        if (!resp.IsSuccessStatusCode)
        {
            DiagnosticLog.Write($"HTTP {(int)resp.StatusCode} {resp.StatusCode} from {url}");
            throw new InvalidOperationException($"HTTP {(int)resp.StatusCode}");
        }

        var json = await resp.Content.ReadAsStringAsync();
        return JsonSerializer.Deserialize<T>(json)
            ?? throw new InvalidOperationException("parsing response: empty result");
    }

    // Percent-encodes non-ASCII and control characters in a cookie value using
    // the Latin-1 byte of each character (which equals the original plaintext
    // byte for values decoded via Encoding.Latin1).
    private static string PercentEncode(string value)
    {
        if (value.All(c => c is > ' ' and < '\x7F' and not '"' and not ',' and not ';' and not '\\' and not '%'))
            return value;

        var sb = new StringBuilder(value.Length * 3);
        foreach (char c in value)
        {
            if (c is > ' ' and < '\x7F' and not '"' and not ',' and not ';' and not '\\' and not '%')
                sb.Append(c);
            else
                sb.Append('%').Append(((int)c & 0xFF).ToString("X2"));
        }
        return sb.ToString();
    }
}
